---
title: "Visualizations for Inforgraphic"
author: "Sofia Sarak"
format: html
editor: visual
---

Read in Data

```{r}
#| warning: false
#| message: false
#| echo: false
# Load necessary packages
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(patchwork)
library(maps)
library(geomtextpath)
library(showtext)

# for bubble chart
library(packcircles)
library(ggforce)
library(treemap)
```

```{r}
#| echo: false
#| message: false
#| warning: false

# Load fall quarter data
fall <- read_csv(here("data/fall_posts.csv")) %>% 
  clean_names() %>%
  
  mutate(season = "fall") %>% 
  
  mutate(region = case_when(
    city == "Washington, DC" ~ "Washington,D.C.",
    
    state == "AB" ~ NA,
    
    state == "AK" ~ "Alaska",
    
    state == "HI" ~ "Hawaii",
    
    state %in% c("Multiple", "TX/NM") ~ NA,
    
    # West Coast
    state %in% c("CA", "OR", "WA") ~ "West Coast",
    
    # Southwest
    state %in% c("AZ", "NM", "TX", "NV") ~ "Southwest",
    
    # Rocky Mountains
    state %in% c("CO", "UT", "WY", "MT", "ID") ~ "Rocky Mountains",
    
    # Great Plains
    state %in% c("ND", "SD", "NE", "KS", "OK", "IA", "MO") ~ "Great Plains",
    
    # Great Lakes
    state %in% c("MN", "WI", "MI", "IL", "IN", "OH") ~ "Great Lake",
    
    # Mideast
    state %in% c("NY", "NJ", "PA", "DE", "MD", "DC") ~ "Mideast",
    
    # New England
    state %in% c("ME", "NH", "VT", "MA", "RI", "CT") ~ "New England",
    
    # Southeast
    state %in% c("VA", "WV", "KY", "TN", "NC", "SC", "GA",
                 "FL", "AL", "MS", "AR", "LA") ~ "Southeast",
    
    # Default (keeps state abbreviation if unmatched)
    TRUE ~ state
  )) %>% 
  mutate(position_type = str_replace(position_type, "reseacher", "researcher"),
         position_type = str_replace(position_type, "specialist", "data specialist"),
         position_type = str_replace(position_type, "data data specialist", "data specialist"),
         position_type = str_replace(position_type, "machine learning data specialist", "machine learning specialist"))

# Load winter quarter data
winter <- read_csv(here("data/winter_posts.csv")) %>% 
  clean_names() %>%
  mutate(yearly_salary_min = as.numeric(yearly_salary_min),
         yearly_salary_max = as.numeric(yearly_salary_max)) %>% 
  
   mutate(season = "winter",
          sector = case_when(
            sector == "International Organization" ~ "Federal Government",
            TRUE ~ sector
          )) %>% 
  
  mutate(region = case_when(
    city == "Washington, DC" ~ "Washington,D.C.",
    
    state == "AB" ~ NA,
    
    state == "AK" ~ "Alaska",
    
    state == "HI" ~ "Hawaii",
    
    state %in% c("Multiple", "TX/NM") ~ NA,
    
    # West Coast
    state %in% c("CA", "OR", "WA") ~ "West Coast",
    
    # Southwest
    state %in% c("AZ", "NM", "TX", "NV") ~ "Southwest",
    
    # Rocky Mountains
    state %in% c("CO", "UT", "WY", "MT", "ID") ~ "Rocky Mountains",
    
    # Great Plains
    state %in% c("ND", "SD", "NE", "KS", "OK", "IA", "MO") ~ "Great Plains",
    
    # Great Lakes
    state %in% c("MN", "WI", "MI", "IL", "IN", "OH") ~ "Great Lake",
    
    # Mideast
    state %in% c("NY", "NJ", "PA", "DE", "MD", "DC") ~ "Mideast",
    
    # New England
    state %in% c("ME", "NH", "VT", "MA", "RI", "CT") ~ "New England",
    
    # Southeast
    state %in% c("VA", "WV", "KY", "TN", "NC", "SC", "GA",
                 "FL", "AL", "MS", "AR", "LA") ~ "Southeast",
    
    # Default (keeps state abbreviation if unmatched)
    TRUE ~ state
  )) %>% 
  mutate(position_type = str_replace(position_type, "reseacher", "researcher"),
         position_type = str_replace(position_type, "specialist", "data specialist"),
         position_type = str_replace(position_type, "data data specialist", "data specialist"),
         position_type = str_replace(position_type, "machine learning data specialist", "machine learning specialist"))

# combine the two
all_posts <- bind_rows(fall, winter)
```

Save theme colors
```{r}
bren_blue <- "#003660"
bren_green <- "#78a441"
apricot <- "#F5CDA7"
tangerine <- "#FAA381"
lavender <- "#8E9AAF"
sky_blue <- "#76BED0"
ivory <- "#F5F9E9"

font_add_google(name = "IBM Plex Sans", family = "plex")

# Create theme for all visualizations
report_theme <- theme_classic() +
  theme(axis.title.y = element_blank())
```

```{r}
skills_pal <- c(
  "R" = bren_blue,
  "GIS" = bren_green,
  "SQL" = tangerine,
  "Excel" = lavender,
  "Python" = sky_blue,
  "Power BI" = apricot
)
```


Sectors: Bar Chart
```{r}
showtext_auto(enable = TRUE)

all_posts %>% 
  group_by(sector) %>% 
  summarize(count = n()) %>% 
ggplot(aes(x = reorder(sector, count), y = count)) +
  geom_col(color = bren_blue, fill = alpha(bren_blue, 0.8)) + # position = "dodge"
  geom_text(aes(label = count), hjust = -1,
            color = ivory) +
  labs(y = " ") +
  coord_flip() +
  report_theme +
  scale_x_discrete(position = "top") +
  scale_y_reverse() +
  theme(
   axis.text = element_text(family = "plex"),
   axis.line.x = element_blank(),
   axis.text.x = element_blank(),
   axis.ticks.x = element_blank()
  )

ggsave("plots/sector.pdf")

showtext_auto(enable = FALSE)
```



Prepare data to make packed bubble chart (or use area chart?? like with the boxes)
```{r}
all_bubble <- all_posts %>% 
  count(environmental_field, sort = TRUE) %>% 
  head(9) %>%
  
  # Capitalize environmental fields
  mutate(environmental_field_cap = case_when(
    environmental_field == "geospatial" ~ "Geospatial Analysis",
    environmental_field == "sustainability" ~ "Sustainability",
    environmental_field == "water/coastal" ~ "Water/Coastal",
    environmental_field == "energy and infrastructure" ~ "Energy & Infrastructure",
    environmental_field == "resource management" ~ "Resource Management",
    environmental_field == "climate" ~ "Climate",
    environmental_field == "conservation" ~ "Conservation",
    environmental_field == "policy" ~ "Policy",
    environmental_field == "agriculture" ~ "Agriculture",
    #environmental_field == "communication" ~ "Communication",
    TRUE ~ environmental_field
  )) %>% 
  
  mutate(circleProgressiveLayout(n, sizetype = "area"),
         label = paste0(environmental_field_cap))
  
 
```

Bubble chart
```{r}
showtext_auto(enable = TRUE)

ggplot(all_bubble, aes(x0 = x, y0 = y)) +
  geom_circle(aes(r = radius), fill = alpha(bren_green, 0.8), color = bren_green) +
  geom_text(aes(x = x, y = y, label = paste0(label, "\n", n)),
            color = ivory, family = "plex") +
  theme_void()

ggsave("plots/bubble.pdf")

showtext_auto(enable = FALSE)
```
Treemap trial
```{r}
#| execute: false
all_posts %>% 
  count(environmental_field, sort = TRUE) %>% 
  head(7) %>%
  treemap(
        index = "environmental_field",
        vSize = "n",
        type = "index")
```
Skills treemap
```{r}
#| echo: false
# Create columns that contain TRUE/FALSE values for hard skills mentioned
all_skills <- all_posts %>% 
  mutate(R_req = stringr::str_detect(all_posts$hard_skills, "R"), 
         Python_req = stringr::str_detect(all_posts$hard_skills, "Python"),
         GIS_req = stringr::str_detect(all_posts$hard_skills, "GIS"),
         Excel_req = stringr::str_detect(all_posts$hard_skills, "Excel"),
         SQL_req = stringr::str_detect(all_posts$hard_skills, "SQL"),
         Power_req = stringr::str_detect(all_posts$hard_skills, "Power BI"))

# Create data frame with the number of positions that mentioned each skill
skills <- c("R", "Python", "GIS", "Excel", "SQL", "Power BI")

skills_sum <- c(sum(all_skills$R_req, na.rm = TRUE), sum(all_skills$Python_req, na.rm = TRUE), sum(all_skills$GIS_req, na.rm = TRUE), sum(all_skills$Excel_req, na.rm = TRUE), sum(all_skills$SQL_req, na.rm = TRUE), sum(all_skills$Power_req, na.rm = TRUE))

skills_count <- data.frame(skills, skills_sum) %>% 
  mutate(percent = round(skills_sum/nrow(all_posts) * 100),
         label = paste0(skills, "\n", percent, "%"))

skills_count %>% 
  treemap(
    index = "label",
    vSize = "skills_sum",
    type = "index"
  )
```

```{r}
library(treemapify)

showtext_auto(enable = TRUE)

# Build treemap with custom labels
ggplot(skills_count, aes(area = skills_sum, label = label)) +
                         #fill = skills)) + # Combine labels in aes
  geom_treemap(alpha = 0.8, color = ivory, fill = bren_blue) +
  geom_treemap_text(
    place = "centre", # Position
    size = 12,        # Font size
    color = ivory,  # Font color
    family = "plex",  # Font family
    grow = TRUE,
    reflow = TRUE
  ) +
  scale_fill_manual(values = skills_pal) +
  theme(legend.position = "none") # Remove legend 

ggsave("plots/skills.pdf")

showtext_auto(enable = FALSE)
```

```{r}
#| execute: false
# Plot data frame
ggplot(skills_count, aes(x = reorder(skills, skills_sum), y = skills_sum)) +
  geom_col(color = bren_blue,
           fill = alpha(bren_blue, 0.8)) +
  geom_text(aes(label = skills_sum), hjust = -0.5) +
  coord_flip() +
  labs(y = "Number of Positions", 
       x = "Hard Skill Mentioned") +
  theme_classic()
```

Position details bar charts
```{r}
library(patchwork)

showtext_auto(enable = TRUE)

commitment <- all_posts %>% 
  group_by(term) %>% 
  summarize(count = n()) %>% 
  filter(term != "part-time") %>% 
ggplot(aes(x = reorder(term, -count), y = count)) + 
  geom_bar(stat = "identity",
           color = bren_blue,
           fill = alpha(bren_blue, 0.8)) +
  geom_text(aes(label = count), vjust = 1.5,
            color = ivory) +
  labs(title = "Commitment Length",
       y = "Number of Positions") +
  theme_classic() +
  scale_x_discrete(labels = c("Permanent", "Limited Term")) +
  theme(axis.title.x = element_blank(),
        text = element_text(family = "plex")) +
  ylim(0, 200)

type <- all_posts %>% 
  mutate(job_type = case_when(
    job_type == "short-term project" ~ "internship",
    TRUE ~ job_type)) %>% 
  group_by(job_type) %>% 
  summarize(count = n()) %>% 
ggplot(aes(x = reorder(job_type, -count), y = count)) + 
  geom_bar(stat = "identity",
           color = bren_blue,
           fill = alpha(bren_blue, 0.8)) +
  geom_text(aes(label = count), vjust = 1.5,
            color = ivory) +
  labs(title = "Position Type",
       y = "Number of Positions") +
  theme_classic() +
  scale_x_discrete(labels = c("Full-time", "Internship", "Fellowship", "Part-time")) +
  theme(axis.title.x = element_blank(),
        text = element_text(family = "plex")) +
  ylim(0, 200)

# * note that short term project was lumped into internship!

modality <- all_posts %>% 
  group_by(modality) %>% 
  summarize(count = n()) %>% 
ggplot(aes(x = reorder(modality, -count), y = count)) + 
  geom_bar(stat = "identity",
           color = bren_blue,
           fill = alpha(bren_blue, 0.8)) +
  geom_text(aes(label = count), vjust = 1.5,
            color = ivory) +
  labs(title = "Modality", y = "Number of Positions") +
  theme_classic() +
   scale_x_discrete(labels = c("On-site", "Hybrid", "Remote", "Remote Option", "Hybrid Option")) +
  theme(axis.title.x = element_blank(),
        text = element_text(family = "plex")) +
  ylim(0, 150)

commitment / type / modality +
  plot_layout(axes = "collect")

ggsave("plots/position_type2.pdf", height = 6)

showtext_auto(enable = FALSE)
```

Salary
```{r}

showtext_auto(enable = TRUE)
all_posts %>% 
  mutate(median_salary = (yearly_salary_min + yearly_salary_max)/2) %>% 
  filter(median_salary != 0,
         job_type != "part-time",
         job_type != "internship") %>% 
  
  ggplot(aes(y = median_salary, x = reorder(sector, median_salary))) + 
  geom_boxplot(color = bren_green,
           fill = alpha(bren_green, 0.5)) +
  labs(y = "Annual Compensation (US Dollars)",
       x = " ") +
  theme_minimal() +
  theme(text = element_text(family = "plex"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_text(margin = margin(r = 8))) +
  
  # styling labels for spacing
  
  scale_x_discrete(labels = c("Non-profit/\nNGO", "Research/\nEducation", 
                              "State\nGovernment", "Consulting", "Federal\nGovernment",
                              "Local\nGovernment", "Corporate")) +
  scale_y_continuous(labels = scales::label_number(scale = 1e-3, suffix = "k"))
  
 # geom_labelvline(xintercept = median_salary, 
                 # color = bren_green, label = "Median Salary: $74850",
                  #size = 3) 

#ggsave("plots/salary_vert.pdf")

showtext_auto(enable = FALSE)
```

Location map
```{r}
# map of United States

state_counts <- all_posts %>%
  filter(!is.na(state)) %>%
  count(state) %>% 
  
  # replace NA values with 0
  mutate(count = replace_na(n, 0)) %>% 
  
  # bin state counts
  mutate(count_bin = cut(n,
                         breaks = c(-1, 0, 5, 10, 20, 80, 100),
                         labels = c("0", "Below 5", "6-10", "10-20", "20-80", "Over 80"),
                         include.lowest = TRUE))

# load in lat and long of US states from map library
us_map <- map_data("state")

# add a column that matches state abbreviation to its name
state_counts <- state_counts %>%
  mutate(
    region = tolower(state.name[match(state, state.abb)])
  )

showtext_auto(enable = TRUE)

# join and plot
us_map %>%
  left_join(state_counts, by = "region") %>%
  ggplot(aes(long, lat, group = group, fill = count_bin)) +
  geom_polygon(color = "gray90", linewidth = 0.2) +
  
  #geom_text(aes(x = x, y = y, label =n),
            #color = bren_blue, family = "plex") +

  coord_fixed(1.3) +
  scale_fill_manual(
  values = c("#F0F4EB", "#C6D4B2", "#9DB979", "#78A441"),
  na.value = "grey99"
) +
 labs(fill = " ") +
  theme_void() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
     plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm")
  )

showtext_auto(enable = FALSE)

#ggsave("plots/map.pdf")
```

