---
title: "EDS Job Market: October 2025 - May 2026"
author: "Sofia Sarak"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
# Load necessary packages
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(patchwork)
library(maps)
library(geomtextpath)

# theme
bren_blue <- "#003660"
bren_green <- "#78a441"
lavender <- "#8E9AAF"
ivory <- "#F5F9E9"

# sectors
consulting <- "#264653"
corporate <- "#287271"
federal_gov <- "#2a9d8f"
local_gov <- "#8ab17d"
nonprofit <- "#e9c46a"
research <- "#f4a261"
state_gov <- "#e76f51"
```

```{r}
#| message: false
#| warning: false
# read in data
# Load fall quarter data
fall <- read_csv(here("data/fall_posts.csv")) %>% 
  clean_names() %>%
  
  # Denote that these data come from the fall quarter
  mutate(season = "fall",
         total_season = n())

# Load winter quarter data
winter <- read_csv(here("data/winter_posts.csv")) %>% 
  clean_names() %>%
  
  # Denote that these data come from the fall quarter
  mutate(season = "winter",
         total_season = n(),
         
         # salary columns got read in as characters :/
         
         yearly_salary_min = as.numeric(yearly_salary_min),
         yearly_salary_max = as.numeric(yearly_salary_max)) %>% 
  
   # Fix observations to match standards
   mutate(sector = case_when(
          sector == "International Organization" ~ "Federal Government",
          TRUE ~ sector))

# Load spring quarter data
spring <- read_csv(here("data/spring_posts.csv")) %>% 
  clean_names() %>% 
  
  # Denote that these data come from the spring quarter
  mutate(season = "spring",
         total_season = n())
```

```{r}
#| echo: false
#| message: false
#| warning: false
# calculate yearly salary for spring 
spring <- spring %>% 
  
  # create annual salary columns
  mutate(annual_salary_min = ifelse(hourly == "Yes", salary_minimum * 37.5 * 50, salary_minimum),
         annual_salary_max = ifelse(hourly == "Yes", salary_maximum * 37.5 * 50, salary_maximum),
         
         # repeat but for monthly salaries
         annual_salary_min = ifelse(monthly == "Yes", salary_minimum * 12, annual_salary_min),
         annual_salary_max = ifelse(monthly == "Yes", salary_maximum * 12, annual_salary_max))

# change column names for fall and winter
fall <- rename(fall, c(annual_salary_min = yearly_salary_min, annual_salary_max = yearly_salary_max))
winter <- rename(winter, c(annual_salary_min = yearly_salary_min, annual_salary_max = yearly_salary_max))

# have to rename some spring columns as well
spring <- rename(spring, c(employer = company_name, modality = work_arrangement, term = permanent_or_limited_term,
                           minimum_degree = minimum_degree_required, experience_years = years_of_experience,
                           compensation_minimum = salary_minimum, compensation_maximum = salary_maximum, 
                           hard_skills = technical_skills))
```

```{r}
#| echo: false
#| message: false
#| warning: false
all <- bind_rows(fall, winter, spring)

all_clean <- all %>% 
  
  # Apply geographic groupings for summaries and viz
  mutate(region = case_when(
    city == "Washington, DC" ~ "Washington,D.C.",
    
    state == "AB" ~ NA,
    
    state == "AK" ~ "Alaska",
    
    state == "HI" ~ "Hawaii",
    
    state %in% c("Multiple", "TX/NM") ~ NA,
    
    # West Coast
    state %in% c("CA", "OR", "WA") ~ "West Coast",
    
    # Southwest
    state %in% c("AZ", "NM", "TX", "NV") ~ "Southwest",
    
    # Rocky Mountains
    state %in% c("CO", "UT", "WY", "MT", "ID") ~ "Rocky Mountains",
    
    # Great Plains
    state %in% c("ND", "SD", "NE", "KS", "OK", "IA", "MO") ~ "Great Plains",
    
    # Great Lakes
    state %in% c("MN", "WI", "MI", "IL", "IN", "OH") ~ "Great Lake",
    
    # Mideast
    state %in% c("NY", "NJ", "PA", "DE", "MD", "DC") ~ "Mideast",
    
    # New England
    state %in% c("ME", "NH", "VT", "MA", "RI", "CT") ~ "New England",
    
    # Southeast
    state %in% c("VA", "WV", "KY", "TN", "NC", "SC", "GA",
                 "FL", "AL", "MS", "AR", "LA") ~ "Southeast",
    
    # Default (keeps state abbreviation if unmatched)
    TRUE ~ state))  %>% 
  
  mutate(annual_salary_med = ((annual_salary_min + annual_salary_max)/2))

# the `position_type` is a little messy, and will remain messy
```

```{r}
# time series wrangling

# split date posted column into three 
all_clean["month"] = str_split_i(all_clean$date_posted, " ", 1)
```

```{r}
time_series_sector <- all_clean %>% 
  group_by(sector, month) %>% 
  summarize(count = n()) %>% 
  drop_na()
```

```{r}
ggplot(time_series_sector, aes(x = month, y = count, 
                               color = as.factor(sector), 
                               group = as.factor(sector))) +
  geom_line(linewidth = 1.5) +
  scale_color_manual(values = c(consulting, corporate, federal_gov, local_gov, nonprofit, research, state_gov)) +
  theme_minimal() +
  labs(color = " ",
       y = "Number of Jobs") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) 

ggsave("sectors_time.png", width = 9)
```
```{r}
time_series_all <- all_clean %>% 
  group_by( month) %>% 
  summarize(count = n()) %>% 
  drop_na()

```

```{r}
# try ordering months
time_series_all$month <- factor(time_series_all$month, levels = c("October", "November", "December", "January", "February", "March", "April", "May"))
```


```{r}
ggplot(time_series_all, aes(x = month, y = count, group = 1)) +
  geom_line(color = bren_blue, linewidth = 1.7) + 
  theme_minimal() +
  labs(y = "Number of Positions", 
       x = " ") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank())

ggsave("all_time.png", width = 9)
```


```{r}
# try ordering months
time_series_sector$month <- factor(time_series_sector$month, levels = c("October", "November", "December", "January", "February", "March", "April", "May"))
```

```{r}
all_clean <- all_clean %>% 
  group_by(season, sector) %>% 
  mutate(perc_sector = n()/total_season)

ggplot(all_clean, aes(y = sector,  fill = season)) +
  geom_bar() 
 # facet_wrap(~season, nrow = 3)
```

```{r}
ggplot(all_clean, aes(y = job_type,  fill = season)) +
  geom_bar(position = "stack") # figure out how to do %!
```

```{r}
# term time series
time_series_term <- all_clean %>% 
  group_by(job_type, month) %>% 
  summarize(count = n()) %>% 
  drop_na()
```

```{r}
# attempt salary hist
ggplot(all_clean, aes(x = annual_salary_med, fill = sector)) +
  geom_density(alpha = 0.7) + # or histogram!
  facet_wrap(~sector, nrow = 7) +
   scale_fill_manual(values = c(consulting, corporate, federal_gov, local_gov, nonprofit, research, state_gov)) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(y = " ",
       x = "Annual Median Salary (USD)")

ggsave("sectors_salary.png", width = 6)
```

```{r}
all_clean <- all_clean %>% 
  mutate(R_req = stringr::str_detect(hard_skills, "R"), 
         Python_req = stringr::str_detect(hard_skills, "Python"),
         GIS_req = stringr::str_detect(hard_skills, "GIS"),
         Excel_req = stringr::str_detect(hard_skills, "Excel"),
         SQL_req = stringr::str_detect(hard_skills, "SQL"),
         Power_req = stringr::str_detect(hard_skills, "Power BI"),
         spatial_req = stringr::str_detect(hard_skills, "Spatial analysis"),
         remote_req = stringr::str_detect(hard_skills, "Remote"),
         tab_req = stringr::str_detect(hard_skills, "Tableau"),
         stata_req =  stringr::str_detect(hard_skills, "STATA"))

# Create data frame with the number of positions that mentioned each skill
skills <- c("R", "Python", "GIS", "Excel", "SQL", "Power BI", "Spatial analysis", "Remote sensing", "Tableau", "Stata")
skills_sum <- c(sum(all_clean$R_req, na.rm = TRUE), 
                sum(all_clean$Python_req, na.rm = TRUE), 
                sum(all_clean$GIS_req, na.rm = TRUE), 
                sum(all_clean$Excel_req, na.rm = TRUE), 
                sum(all_clean$SQL_req, na.rm = TRUE), 
                sum(all_clean$Power_req, na.rm = TRUE),
                sum(all_clean$spatial_req, na.rm = TRUE),
                sum(all_clean$remote_req, na.rm = TRUE),
                sum(all_clean$tab_req, na.rm = TRUE),
                sum(all_clean$stata_req, na.rm = TRUE))

skills_count <- data.frame(skills, skills_sum)

```

Is there a way to make str_detect case insensitive?


```{r}
all_clean %>% 
  group_by(sector) %>% 
  summarize(count = n()) %>% 
ggplot(aes(x = reorder(sector, count), y = count, fill = sector)) +
  geom_col() + # position = "dodge"
  geom_text(aes(label = count), hjust = 1.5,
            color = ivory) +
  labs(y = " ",
       x = " ") +
  coord_flip() +
  #report_theme() +
  #scale_x_discrete(position = "top") +
  #scale_y_reverse() +
  theme_minimal() +
  theme(
   axis.line.x = element_blank(),
   axis.text.x = element_blank(),
   axis.ticks.x = element_blank(),
   panel.grid = element_blank(),
   legend.position = "none"
  ) +
   scale_fill_manual(values = c(consulting, corporate, federal_gov, local_gov, nonprofit, research, state_gov))

ggsave("sector.png", width = 9)
```
```{r}
all_clean %>% 
  
   mutate(environmental_field = case_when(
    is.na(environmental_field) ~ "other data analysis",
    TRUE ~ environmental_field)) %>% 
  
  group_by(environmental_field) %>% 
  summarize(count = n()) %>% 
  slice_max(order_by = count, n = 10) %>% 
ggplot(aes(x = count, y = reorder(environmental_field, count))) + 
  geom_bar(stat = "identity",
           color = bren_blue,
           fill = alpha(bren_blue, 0.7)) +
  geom_text(aes(label = count), hjust = 1.5,
            color = ivory) +
  labs(x = " ",
       y = " ") +
  theme_minimal() +
   theme(
   axis.line.x = element_blank(),
   axis.text.x = element_blank(),
   axis.ticks.x = element_blank(),
   panel.grid = element_blank()
  ) 
  
ggsave("enviro_field.png", width = 9)
```
```{r}
all_clean %>% 
  group_by(term) %>% 
  summarize(count = n()) %>% 
  filter(term != "part-time") %>% 
ggplot(aes(x = reorder(term, -count), y = count)) + 
  geom_bar(stat = "identity",
           color = bren_blue,
           fill = alpha(bren_blue, 0.7)) +
  geom_text(aes(label = count), vjust = 1.5,
            color = ivory) +
  labs(title = " ",
       y = " ") +
  theme_classic() +
  scale_x_discrete(labels = c("Permanent", "Limited Term", "Part-time")) +
  theme(axis.title.x = element_blank()) +
  ylim(0, 300) +
   theme(
   axis.line.y = element_blank(),
   axis.text.y = element_blank(),
   axis.ticks.y = element_blank(),
   axis.ticks.x = element_blank()
  )

ggsave("commitment.png", width = 9)
```

